---
- hosts: all
  gather_facts: true
  
- hosts: webservers
  become: true
  become_method: sudo
  gather_facts: yes
  tasks:
    - name: apt update
      apt:
        update_cache: yes

    - name: install python3, pip3, venv, and git
      apt:
        name:
          - python3
          - python3-pip
          - python3-venv
          - git
        state: present

    - name: install flask
      pip:
        name: flask
        state: latest

    - name: Installing Gunicorn
      apt:
        name: gunicorn
        state: latest

    - name: Copy flask app to remote server
      copy:
        src: application2.py
        dest: /home/ubuntu/application2.py
        owner: ubuntu
        mode: "0755"

    - name: Running Flask application with Gunicorn
      systemd:
        name: gunicorn
        enabled: yes
        state: started
        daemon_reload: yes
        env:
          FLASK_APP: /home/ubuntu/application2.py
        executable: /usr/bin/gunicorn
        args: 
          - '-w 2'
          - '-b 0.0.0.0:7000'
          - 'application2:app'

- name: Configure HAProxy load balancer
  hosts: HAproxy
  become: true
  become_method: sudo
  tasks:
    - name: apt update and install HAProxy
      apt:
        name: haproxy
        state: latest
        update_cache: yes

    - name: Configure HAProxy
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
      notify: Restart HAProxy

  handlers:
    - name: Restart HAProxy
      service:
        name: haproxy
        state: restarted
