---
- hosts: all
  gather_facts: yes


- name: Configure HAproxy Load Balancer
  hosts: HAproxy
  become: true
  become_method: sudo
  tasks:
    - name: apt update
      apt:
        update_cache: yes
    - name: Install HAProxy
      apt:
        name: haproxy
        state: present

    - name: Configure HAProxy
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
      become: yes
    - name: Restart haproxy
      service:
        name: haproxy
        state: restarted
- hosts: webservers
  become: yes
  become_method: sudo
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
    - name: Install Python3, pip3, and venv
      apt:
        name:
          - python3
          - python3-pip
          - python3-venv
        state: present
    - name: Create flask-app directory
      file:
        path: /home/ubuntu/flask-app
        state: directory
    - name: Change directory to flaskapp
      shell: cd /home/ubuntu/flask-app
    - name: Install virtualenv package
      apt:
        name: python3-virtualenv
        state: present
    - name: Creating virtual environment
      file:
        path: /home/ubuntu/flask-app/venv
        state: directory
        mode: "0755"
    - name: Set up virtual environment
      pip:
        name: Flask
        virtualenv: /home/ubuntu/flask-app/venv
    - name: Set permissions for virtual environment
      become: yes
      become_user: root
      file:
        path: /home/ubuntu/flask-app/venv
        mode: "0755"
        recurse: yes
    - name: Copy Flask app file
      copy:
        src: application2.py
        dest: /home/ubuntu/flask-app/venv/app.py

                                             
